### ISSUE TITLE
Phase 2 Master List

### ISSUE THREAD

**Issue by matthewhively** [matthewhively/sots_mod#128]
- [ ] vaccines without plague research https://github.com/matthewhively/sots_mod/issues/30
- [ ] autonomous ship engine upgrades  https://github.com/matthewhively/sots_mod/issues/98 & https://github.com/matthewhively/sots_mod/issues/7
- [ ] mass driver not 100% for liir https://github.com/matthewhively/sots_mod/issues/125
- [ ] drones only 100% morrigi https://github.com/matthewhively/sots_mod/issues/124
- [ ] limit mission sections for gates https://github.com/matthewhively/sots_mod/issues/123
- [ ] adjust zuul research https://github.com/matthewhively/sots_mod/issues/110
- [ ] more trade adjustments https://github.com/matthewhively/sots_mod/issues/111 https://github.com/matthewhively/sots_mod/issues/40
- [ ] Improve AI scouting https://github.com/matthewhively/sots_mod/issues/103
- [ ] Stellar drive tweaks https://github.com/matthewhively/sots_mod/issues/18 https://github.com/matthewhively/sots_mod/issues/104
- [ ] Station mods (within reason) https://github.com/matthewhively/sots_mod/issues/48
- [ ] Weapon family affinities https://github.com/matthewhively/sots_mod/issues/100
- [ ] Weap vs armor (within reason) https://github.com/matthewhively/sots_mod/issues/14
- [ ] Boarding Pods (If necessary) https://github.com/matthewhively/sots_mod/issues/96
- [ ] Engine HP scaling https://github.com/matthewhively/sots_mod/issues/95
- [ ] Add missing crew https://github.com/matthewhively/sots_mod/issues/91
- [ ] lv1 XNC bonus (may not be possible) https://github.com/matthewhively/sots_mod/issues/33
- [ ] Planet damage https://github.com/matthewhively/sots_mod/issues/15
- [ ] DN CnC to AM https://github.com/matthewhively/sots_mod/issues/26
- [ ] Mining traps https://github.com/matthewhively/sots_mod/issues/52
- [ ] Defense Platform buffs https://github.com/matthewhively/sots_mod/issues/71 https://github.com/matthewhively/sots_mod/issues/46
- [ ] Nerf Biomes https://github.com/matthewhively/sots_mod/issues/58
- [ ] shields vs shield-breakers https://github.com/matthewhively/sots_mod/issues/38
- [ ] AM warheads https://github.com/matthewhively/sots_mod/issues/27
- [ ] Help AI with Gravboats https://github.com/matthewhively/sots_mod/issues/20
- [ ] Increase maint costs for players https://github.com/matthewhively/sots_mod/issues/12
- [ ] Slower adoption of cruisers https://github.com/matthewhively/sots_mod/issues/9
- [ ] Deep scan vs Sensor stations https://github.com/matthewhively/sots_mod/issues/8
- [ ] MISC catchall (possibly split up) https://github.com/matthewhively/sots_mod/issues/112

Test and confirm:
hiver freighters https://github.com/matthewhively/sots_mod/issues/117
PD tech adjustments https://github.com/matthewhively/sots_mod/issues/57 <<< does this make sense?
Nerf PD https://github.com/matthewhively/sots_mod/issues/37 <<< how much of this was already completed?
Gravity to AM https://github.com/matthewhively/sots_mod/issues/32
